# Generated by Django 5.0.7 on 2024-07-30 18:08

import crudapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='Dateoforder',
            field=models.DateField(default=crudapp.models.current_time, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='Product',
            field=models.CharField(choices=[('Asus Laptop', 'Asus Laptop'), ('Leonovo Laptop', 'Leonovo Laptop'), ('Dell Laptop', 'Dell Laptop'), ('Hp Laptop', 'Hp Laptop'), ('Acer Laptop', 'Acer Laptop')], max_length=20),
        ),
    ]
